export const GET_ALL_INTERNSHIPS = "GET_ALL_INTERNSHIPS";
export const GET_SINGLE_INTERNSHIPS = "GET_SINGLE_INTERNSHIPS";
export const CREATE_INTERNSHIP = "CREATE_INTERNSHIP";
export const EDIT_INTERNSHIP = "EDIT_INTERNSHIP";
export const DELETE_INTERNSHIP = "DELETE_INTERNSHIP";